# Generated by Django 5.2.4 on 2025-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250706_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_flats', to='property.owner', verbose_name='Собственники'),
        ),
    ]
