# Generated by Django 5.2.4 on 2025-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, help_text='Отметьте, если квартира в новостройке', null=True, verbose_name='Новостройка'),
        ),
    ]
