# Generated by Django 5.2.4 on 2025-07-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_flat_new_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
    ]
